name: "Firebase Authorized Domains"
description: "Control firebase authorized domains from github actions"
author: "WaveZync"
inputs:
  service_account_key_json:
    required: true
    description: >-
      Google Service Account json key content. You can get it from 
      https://console.cloud.google.com/iam-admin/serviceaccounts and store it in github secrets.
      This key should have permission to edit firebase project, google cloud cloud platform(with Editor role).
  action:
    required: true
    description: >-
      Action to perform. Available actions are: add, remove
    default: "add"
  domain:
    required: true
    description: >-
      Domain to add or remove
runs:
  using: "node16"
  main: "dist/index.js"
